### PR TITLE
Test for rendering specific user and all users

### LINKED ISSUE #291: Add backend unit tests for user controller
**Is your feature request related to a problem? Please describe.**
There are not enough unit tests to cover all the functionality in the user controller.

**DoD**
- Added unit tests for user controller.
- There should be tests updating and reading users

### PR DESCRIPTION
**Pull request by te4-alexander-kjellberg1**
## ⚙️ What issue did you implement or fix?
Fixes #291 

## 📜 Summary
Test for rendering specific user and all users

## 📝 Type of change

Please delete options that are not relevant.

- [x] ✨ New feature or enhancement (non-breaking change which adds functionality)

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Review by te4-alexander-nylundgomes — APPROVED** [review]
Great!

**Review by te4-david-jensen — COMMENTED** [review]
Please review your older, unmerged, pull request(s) before creating new one(s)

**Review by te4-alexander-kjellberg — APPROVED** [review]
Can't say I understand what this test actually does, but it won't break anything!

**Comment by te4-alexander-kjellberg1** [comment]
> Can't say I understand what this test actually does, but it won't break anything!

Setup gets a specific user saved as @user and @users gets all users, the tests then checks if it revived a user on the first test and users on the secound test

**Pull request merged**
