### PR TITLE
Refactored LibraryView.vue and related components to Composition API.

### LINKED ISSUE #441: Refactor library page
## ✨ Feature request
Use composition API instead of option API. 

### 📜 Acceptance Criteria
- [ ] LoanListComponent
- [ ] LibraryLoanComponent
- [ ] TitleListComponent
- [ ] ReturnLoanComponent

### 💡 Additional context
Relates to #350

### PR DESCRIPTION
**Pull request by te4-alexander-kjellberg**
## ⚙️ What issue did you implement or fix?
Fixes #441 

## 📜 Summary
- Refactored code from the old Options API to the newer (and better?) Composition API. 
- This will help make the transition to Vue3 easier when fully released. 
- Removed usage of 'this'. 

## 📝 Type of change

Please delete options that are not relevant.

- [x] ✨ New feature or enhancement (non-breaking change which adds functionality)
- [ ] 📚 This change requires a documentation update

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by te4-alexander-kjellberg** [comment]
Ajaj, många tester som inte gick igenom...

**Comment by itggot-linus-styren** [comment]
> Ouch, quite a few tests failed...

most of the tests that fail are because typescript errors. For the router, you may need to specify the RouteConfig[] type. Use this as reference: https://github.com/daggerok/tsx-vue-composition-api-example#tsx-vuerouter-integration-fixes

> 'this' is not supposed to exist in setup()

You don't need to use this, simply add emit to be included in the object destruction as the second argument to setup function. Take a look at how it was done in 9003ce0cb508cd220c9262a4bf184e3ece6daf68

**Comment by te4-alexander-kjellberg** [comment]
Looks good!

**Review by te4-andre-skvarc — CHANGES_REQUESTED** [review]
Good work! But I can't approve until it passes the necessary tests for merging!

**Review by te4-henrik-stahl — APPROVED** [review]
This is some pretty sweet code you got here kiddo, keep it up sport!

**Review by TE4-Filip-Liljenberg — APPROVED** [review]
Good job!

**Review by itggot-linus-styren — CHANGES_REQUESTED** [review]
Tests now pass, please delete package-lock.json before merge

**Review by itggot-linus-styren — APPROVED** [review]
Looks good, will merge

**Pull request merged**
