### PR TITLE
teacher-profile-page

### LINKED ISSUE #573: Add respective books to respective teacher in their Profile
As a teacher, you want to access all your coursebooks in your profile

- [ ] Overview of books

- [ ] Which books are borrowed/not borrowed?

- [ ] Which student borrowed it?

### PR DESCRIPTION
**Pull request by ntijoh-axel-ostan**
## ⚙️ What issue did you implement or fix?
Fixade att teachers har sin egna profile view istället för standard

## 📝 Type of change

Please delete options that are not relevant.

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ✨ New feature or enhancement (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📚 This change requires a documentation update

## ✅ Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## 💩 How can this implementation be improved?
Ta bort hård kodning på subject/Skönlitteratur och göra den dynamisk

close #573

### CODE REVIEW

**Review by ntijoh-Erik-Albinsson — COMMENTED** [review]
Make sure the tests pass before pushing your code ;()

**Comment by olantig** [comment]
Please fix frontend lint issues before merging.

**Review by ntijoh-nikki-andersson — APPROVED** [review]
Good job!

**Review by ntijoh-Erik-Albinsson — APPROVED** [review]
Very nice improvments

**Pull request merged**
