### PR TITLE
Feature/511 update status when returning book

### LINKED ISSUE #511: When returning a book you should be able to update the books status
### 📇 User story
I don't like to dig through menus just to change the state of a book that was returned.

### 📜 Acceptance Criteria
A list of changes that need to be implemented to consider this feature done.
- [ ] The return page should allow for updating the status of the returned book

### PR DESCRIPTION
**Pull request by te4-jonathan-ronsten**
## ⚙️ What issue did you implement or fix?
Fixes #511 

## 📜 Summary
- Upon returning a book you are now given the opportunity to change condition on the book.
- Added unit testing for this functionality
- added e2e testning this functionality

## 📝 Type of change

Please delete options that are not relevant.

- [x] ✨ New feature or enhancement (non-breaking change which adds functionality)

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## 💩 How can this implementation be improved?
- Change bar into zar. :shipit:

### CODE REVIEW

**Review by te4-andre-skvarc — APPROVED** [review]
Looks good, nice with the tests! This ensures that everything is working correctly!

**Review by te4-andre-skvarc — CHANGES_REQUESTED** [review]
Looks good, nice with the tests! This ensures that everything is working correctly! 
But seems that some GitHub action tests fails...

**Review by te4-andre-skvarc — APPROVED** [review]
Now it looks better! Now we should just fix the deep scan problem in another pull request.

**Review by te4-dennis-christensen — APPROVED** [review]
Looks good now

**Pull request merged**
