### PR TITLE
Update README.md

### LINKED ISSUE #690: Improve README instructions
:shipit:

### PR DESCRIPTION
**Pull request by ntijoh-evelina-karlsson**
Added clearer instructions: clone repository, where to do the docker commands in cli.

## ⚙️ What issue did you implement or fix?
Fixes #690

## 📜 Summary
- Improves the README file to make the instructions clearer

## 📝 Type of change

- [x] ✨ New feature or enhancement (non-breaking change which adds functionality)

## ✅ Checklist:

- [x] I have performed a self-review of my own code

### CODE REVIEW

**Review by ntijoh-my-lovell — COMMENTED** [review]
good

**Review by ntijoh-Erik-Albinsson — COMMENTED** [review]
good

**Review by ntijoh-my-lovell — COMMENTED** [review]
nice nice

**Review by ntijoh-Erik-Albinsson — APPROVED** [review]
ok

**Review by ntijoh-my-lovell — APPROVED** [review]

**Pull request merged**
