### PR TITLE
Availability for books

### PR DESCRIPTION
**Pull request by te4-alexander-kjellberg1**
## ⚙️ What issue did you implement or fix?
A start on fix for #369

## 📜 Summary
- Added in BookFormComponent so you can set a books availability to true or false where, true = available and false = not available

## 📝 Type of change
- [x] ✨ New feature or enhancement (non-breaking change which adds functionality)

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## 💩 How can this implementation be improved?
- Next step is to add so that you can change that true/false value from the website. 
Example, a book can be added as not available but changed in to be available

### CODE REVIEW

**Comment by te4-david-jensen** [comment]
The failing API-tests are as expected. I can fix them after merge.

**Comment by te4-david-jensen** [comment]
Also note that this would require everyone to use rails db:migrate, as it adds a column to the books-table.

**Comment by itggot-linus-styren** [comment]
> Also note that this would require everyone to use rails db:migrate, as it adds a column to the books-table.

Better for everyone else to run rails db:schema:load

**Comment by itggot-linus-styren** [comment]
@te4-alexander-kjellberg1 to resolve conflict, please run rails db:rollback on your branch, rebase with develop and then db:migrate

**Comment by te4-alexander-kjellberg1** [comment]
> @te4-alexander-kjellberg1 to resolve conflict, please run rails db:rollback on your branch, rebase with develop and then db:migrate

We in blue team agreed with the other teams to get back to this pr as well as #591, #553 once we get back from christmas holidays.

So all of this will be resolved in a few weeks

**Review by te4-alexander-nylundgomes — APPROVED** [review]
Great work!

**Review by Te4-Jacob-sandstrom — APPROVED** [review]

**Pull request merged**
