### PR TITLE
Refactored EditBookView and fixed its functionality

### LINKED ISSUE #533: Refactor EditBookView
## Acceptance Criteria
- [ ] View is using composition API
- [ ] The view's components are using composition API
- [ ] No tests break

### PR DESCRIPTION
**Pull request by te4-dennis-christensen**
## ⚙️ What issue did you implement or fix?
Fixes #533

## 📜 Summary
- Refactores EditBookView
- Fixed edit book functionality
- Fixed name error in router

## 📝 Type of change
- [x] ✨ New feature or enhancement (non-breaking change which adds functionality)

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by te4-david-jensen — APPROVED** [review]
Looks good! :shipit:

**Review by TE4-Rasmus-Brednert — APPROVED** [review]
Nice work :)

**Comment by itggot-linus-styren** [comment]
@te4-dennis-christensen why did you merge with e2e tests failing?

**Comment by te4-dennis-christensen** [comment]
> @te4-dennis-christensen why did you merge with e2e tests failing?

What do you mean? All test had green checkmarks next to them when i merged.

**Comment by te4-dennis-christensen** [comment]
Screenshot 2020-12-18 at 16 17 19
this is how the tests looks for me @itggot-linus-styren

**Pull request merged**
