### PR TITLE
Multiple isbn fixat

### LINKED ISSUE #492: It's possible to create multiple titles containing the same ISBN
### Description
There seems like there is a possibility to create multiple titles with the same ISBN identifier.

### Expected behavior
There should only be one title for a specific ISBN

## 🔬 To Reproduce
1. Create a title in the admin titles view
2. Create another one with the same ISBN number
3. Check the title list. There are now two.

### 💡 Additional context
The ISBN column in the db should probably be set to UNIQUE

### PR DESCRIPTION
**Pull request by ntijoh-axel-ostan**
## ⚙️ What issue did you implement or fix?
Fixade att man inte kan skapa flera böcker men samma isbn

## 📝 Type of change
bug

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature or enhancement (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📚 This change requires a documentation update

## ✅ Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

close #492

### CODE REVIEW

**Comment by Linkaan** [comment]
This PR is 5 commits behind develop, consider merging with develop to make sure all checks pass:
```bash
git merge develop
```

**Review by ntijoh-nikki-andersson — CHANGES_REQUESTED** [review]
`setup(props : TitleFormProps, { root, emit } : SetupContext, ) {`
`setup(props : TitleFormProps, { root, emit } : SetupContext) {`

Also the tests aren't going through

**Comment by Linkaan** [comment]
Same issue as described here https://github.com/itggot-TE4/Yabs/pull/776#issuecomment-994891557

**Review by ntijoh-melwin-bruun — APPROVED** [review]
very nice

**Review by ntijoh-nikki-andersson — APPROVED** [review]

**Pull request merged**
