### PR TITLE
Availability is now displayed properly

### LINKED ISSUE #757: Tillgänglighet should be saved as "tillgänglig/ ej tillgänlig" instead of "true/false"
### Description
Creating a book with a selected availability always saves as true or false, but is hard to understand for a non-programer.  

### Expected behaviour
It should be saved with the same availability as the one selected
## 🔬 To Reproduce
Steps to reproduce the behaviour:
1. Create a book
2. select an availability 
3. check the listed books

### PR DESCRIPTION
**Pull request by ntijoh-Erik-Albinsson**
## ⚙️ What issue did you implement or fix?
Fixes #757 

## 📜 Summary
- Availability is displayed in swedish
- fixed some test that was not properly adjusted for the new swedish implementation

## 📝 Type of change

Please delete options that are not relevant.

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature or enhancement (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📚 This change requires a documentation update

## ✅ Checklist:

- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

close #757

### CODE REVIEW

**Review by ntijoh-axel-ostan — APPROVED** [review]
finfint

**Review by ntijoh-nikki-andersson — CHANGES_REQUESTED** [review]
Perhaps a bit too many ternary operators in ListComponent?

**Comment by olantig** [comment]
I think all Tests where changed in #764

**Comment by Linkaan** [comment]
@olantig only e2e tests were addressed there. These changes are valid since they fix the unit tests.

**Review by ntijoh-nikki-andersson — APPROVED** [review]

**Pull request merged**
