### PR TITLE
Test for delete title

### LINKED ISSUE #639: Test for delete title
## Acceptance criteria
- [x] Unit test for delete title
- [x] e2e test for delete title

### PR DESCRIPTION
**Pull request by te4-jonathan-ronsten**
## ⚙️ What issue did you implement or fix?
Fixes #639 

## 📜 Summary
- Added e2e test for delete title
- Added unit test for delete title to see that store have been called

## 📝 Type of change

Please delete options that are not relevant.

- [x] ✨ New feature or enhancement (non-breaking change which adds functionality)

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## 💩 How can this implementation be improved?
- Change bar into zar. :shipit:

### CODE REVIEW

**Review by TE4-David-Sundqvist — CHANGES_REQUESTED** [review]
the code looks good to me but e2e test is failing. please fix e2e and if possible also codeclimate

**Review by TE4-David-Sundqvist — APPROVED** [review]
looks good to me! 👍

**Review by te4-henrik-stahl — APPROVED** [review]
Good job!

**Comment by itggot-linus-styren** [comment]
To fix codeclimate problems consider moving exclude patterns to root level:
image

Also see: https://docs.codeclimate.com/docs/advanced-configuration#section-exclude-patterns
https://github.com/itggot-TE4/Yabs/blob/9393ed58a7f59661e629e04548dc63006cca3efa/.codeclimate.yml#L1-L8

**Pull request merged**
