### PR TITLE
Refactored AdminCardsView and its components

### LINKED ISSUE #537: Refactor AdminCardsView
## Acceptance Criteria
- [ ] View is using composition API
- [ ] The view's components are using composition API
- [ ] No tests break

### PR DESCRIPTION
**Pull request by te4-dennis-christensen**
## ⚙️ What issue did you implement or fix?
Fixes #537

## 📜 Summary
- Refactored AdminCardsView
- Refactored CardFormComponent
- Refactored CanvasContainer
- Refactored CigCanvas
- Corrected tests in AdminCardView.spec.ts

## 📝 Type of change
- [x] ✨ New feature or enhancement (non-breaking change which adds functionality)

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by te4-dennis-christensen** [comment]
@itggot-linus-styren My commit history is a little weird because of a local merge conflict, tips on how i can fix that or at least try to prevent it from happening next time?

**Review by te4-david-jensen — COMMENTED** [review]
Looks good, but is there any specific reason for the 5 deepscan issues remaining?

**Review by te4-tintin-wihlborg — APPROVED** [review]
Ser bra ut. Hittar inget som värkar fel eller som borde ändras.

**Comment by te4-david-jensen** [comment]
> @itggot-linus-styren My commit history is a little weird because of a local merge conflict, tips on how i can fix that or at least try to prevent it from happening next time?

use git reset --soft origin/develop

**Comment by te4-dennis-christensen** [comment]
> Looks good, but is there any specific reason for the 5 deepscan issues remaining?

They existed even before my refactor and its not a part of my current issue to fix it

**Comment by te4-david-jensen** [comment]
> > Looks good, but is there any specific reason for the 5 deepscan issues remaining?
> 
> Some existed even before my refactor and its anyway not a part of my current issue to fix it

👍

**Review by te4-david-jensen — APPROVED** [review]
:shipit:

**Pull request merged**
