### PR TITLE
Excluding duplication check on codeClimate for mocks

### PR DESCRIPTION
**Pull request by te4-adrian-almetun-smeds**
## ⚙️ What issue did you implement or fix?

I'm frustrated when my PR's fail due to valid duplication. So this will exclude them from the duplication cheker. 

## 📜 Summary
- Added codeclimate config
- Excluded __mocks__ in duplication check

## 📝 Type of change

Please delete options that are not relevant.

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ✨ New feature or enhancement (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📚 This change requires a documentation update

## ✅ Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by te4-andre-skvarc — CHANGES_REQUESTED** [review]
Seems good, but ity seems that the github actions tests fails. Check that out! 😃

**Comment by te4-adrian-almetun-smeds** [comment]
> Seems good, but ity seems that the github actions tests fails. Check that out! 😃

It's codeClimate and what should I say. It's the collected debt of two/three groups.

**Review by te4-david-jensen — APPROVED** [review]
Looks good! :shipit:

**Review by te4-andre-skvarc — APPROVED** [review]
Seems good now! :shipit:

**Pull request merged**
