### PR TITLE
Bug/403 seeder

### LINKED ISSUE #403: Seeder crashes when reseeding
### Description
`$ docker-compose run backend rails db:seed:replant fixture=all`
`$ docker-compose run backend rails db:seed fixture=all`
`$ docker-compose run backend rails db:seed:replant` doesn't crash

### Expected behavior
The seeder should not crash when reseeding the database.
## 🔬 To Reproduce
1. Open terminal in Yabs-folder
2. run the latter of the above commands
3. run either of the other commands
4. See error in terminal

### 🔥 Exception or error
`$ docker-compose run backend rails db:seed:replant fixture=all --trace`
<pre><code>
Creating yabs_backend_run ... done
** Invoke db:seed (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Execute db:seed
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke db:load_config 
** Execute db:abort_if_pending_migrations
rails aborted!
ActiveRecord::RecordNotUnique: SQLite3::ConstraintException: UNIQUE constraint failed: books.barcode
/bundle/vendor/gems/sqlite3-1.4.1/lib/sqlite3/statement.rb:108:in `step'
/bundle/vendor/gems/sqlite3-1.4.1/lib/sqlite3/statement.rb:108:in `block in each'
/bundle/vendor/gems/sqlite3-1.4.1/lib/sqlite3/statement.rb:107:in `loop'
/bundle/vendor/gems/sqlite3-1.4.1/lib/sqlite3/statement.rb:107:in `each'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/sqlite3/database_statements.rb:49:in `to_a'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/sqlite3/database_statements.rb:49:in `block (2 levels) in exec_query'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/sqlite3/database_statements.rb:40:in `block in exec_query'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:718:in `block (2 levels) in log'
/usr/local/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:717:in `block in log'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:708:in `log'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/sqlite3/database_statements.rb:39:in `exec_query'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:135:in `exec_insert'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:166:in `insert'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/query_cache.rb:22:in `insert'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/persistence.rb:375:in `_insert_record'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/persistence.rb:933:in `_create_record'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/counter_cache.rb:163:in `_create_record'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/locking/optimistic.rb:70:in `_create_record'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/attribute_methods/dirty.rb:211:in `_create_record'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/callbacks.rb:332:in `block in _create_record'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:135:in `run_callbacks'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:827:in `_run_create_callbacks'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/callbacks.rb:332:in `_create_record'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/timestamp.rb:111:in `_create_record'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/persistence.rb:906:in `create_or_update'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/callbacks.rb:328:in `block in create_or_update'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:135:in `run_callbacks'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:827:in `_run_save_callbacks'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/callbacks.rb:328:in `create_or_update'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/timestamp.rb:129:in `create_or_update'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/persistence.rb:470:in `save'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/validations.rb:47:in `save'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/transactions.rb:315:in `block in save'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:281:in `block in transaction'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
/usr/local/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:281:in `transaction'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/transactions.rb:212:in `transaction'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/transactions.rb:315:in `save'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/suppressor.rb:44:in `save'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/persistence.rb:38:in `create'
/app/db/seeds.rb:44:in `<main>'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:319:in `block in load'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:319:in `load'
/bundle/vendor/gems/railties-6.0.1/lib/rails/engine.rb:556:in `block in load_seed'
/bundle/vendor/gems/railties-6.0.1/lib/rails/engine.rb:676:in `with_inline_jobs'
/bundle/vendor/gems/railties-6.0.1/lib/rails/engine.rb:556:in `load_seed'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/tasks/database_tasks.rb:440:in `load_seed'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/railties/databases.rake:328:in `block (2 levels) in <main>'
/bundle/vendor/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
/bundle/vendor/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
/bundle/vendor/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
/bundle/vendor/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/bundle/vendor/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/bundle/vendor/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
/bundle/vendor/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
/bundle/vendor/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/bundle/vendor/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
/bundle/vendor/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
/bundle/vendor/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
/bundle/vendor/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
/bundle/vendor/gems/railties-6.0.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/bundle/vendor/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/bundle/vendor/gems/railties-6.0.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/bundle/vendor/gems/railties-6.0.1/lib/rails/command.rb:48:in `invoke'
/bundle/vendor/gems/railties-6.0.1/lib/rails/commands.rb:18:in `<main>'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `block in require'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `require'
/app/bin/rails:10:in `<top (required)>'
/bundle/vendor/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
/bundle/vendor/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
/bundle/vendor/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
/bundle/vendor/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
/bundle/vendor/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
/bundle/vendor/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
/bundle/vendor/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/app/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
SQLite3::ConstraintException: UNIQUE constraint failed: books.barcode
/bundle/vendor/gems/sqlite3-1.4.1/lib/sqlite3/statement.rb:108:in `step'
/bundle/vendor/gems/sqlite3-1.4.1/lib/sqlite3/statement.rb:108:in `block in each'
/bundle/vendor/gems/sqlite3-1.4.1/lib/sqlite3/statement.rb:107:in `loop'
/bundle/vendor/gems/sqlite3-1.4.1/lib/sqlite3/statement.rb:107:in `each'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/sqlite3/database_statements.rb:49:in `to_a'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/sqlite3/database_statements.rb:49:in `block (2 levels) in exec_query'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/sqlite3/database_statements.rb:40:in `block in exec_query'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:718:in `block (2 levels) in log'
/usr/local/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:717:in `block in log'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:708:in `log'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/sqlite3/database_statements.rb:39:in `exec_query'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:135:in `exec_insert'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:166:in `insert'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/query_cache.rb:22:in `insert'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/persistence.rb:375:in `_insert_record'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/persistence.rb:933:in `_create_record'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/counter_cache.rb:163:in `_create_record'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/locking/optimistic.rb:70:in `_create_record'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/attribute_methods/dirty.rb:211:in `_create_record'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/callbacks.rb:332:in `block in _create_record'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:135:in `run_callbacks'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:827:in `_run_create_callbacks'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/callbacks.rb:332:in `_create_record'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/timestamp.rb:111:in `_create_record'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/persistence.rb:906:in `create_or_update'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/callbacks.rb:328:in `block in create_or_update'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:135:in `run_callbacks'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:827:in `_run_save_callbacks'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/callbacks.rb:328:in `create_or_update'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/timestamp.rb:129:in `create_or_update'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/persistence.rb:470:in `save'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/validations.rb:47:in `save'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/transactions.rb:315:in `block in save'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:281:in `block in transaction'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
/usr/local/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:281:in `transaction'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/transactions.rb:212:in `transaction'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/transactions.rb:315:in `save'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/suppressor.rb:44:in `save'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/persistence.rb:38:in `create'
/app/db/seeds.rb:44:in `<main>'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:319:in `block in load'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:319:in `load'
/bundle/vendor/gems/railties-6.0.1/lib/rails/engine.rb:556:in `block in load_seed'
/bundle/vendor/gems/railties-6.0.1/lib/rails/engine.rb:676:in `with_inline_jobs'
/bundle/vendor/gems/railties-6.0.1/lib/rails/engine.rb:556:in `load_seed'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/tasks/database_tasks.rb:440:in `load_seed'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/railties/databases.rake:328:in `block (2 levels) in <main>'
/bundle/vendor/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
/bundle/vendor/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
/bundle/vendor/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
/bundle/vendor/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/bundle/vendor/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/bundle/vendor/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
/bundle/vendor/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
/bundle/vendor/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/bundle/vendor/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
/bundle/vendor/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
/bundle/vendor/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
/bundle/vendor/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
/bundle/vendor/gems/railties-6.0.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/bundle/vendor/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/bundle/vendor/gems/railties-6.0.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/bundle/vendor/gems/railties-6.0.1/lib/rails/command.rb:48:in `invoke'
/bundle/vendor/gems/railties-6.0.1/lib/rails/commands.rb:18:in `<main>'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `block in require'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `require'
/app/bin/rails:10:in `<top (required)>'
/bundle/vendor/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
/bundle/vendor/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
/bundle/vendor/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
/bundle/vendor/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
/bundle/vendor/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
/bundle/vendor/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
/bundle/vendor/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/app/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:seed
</code></pre>
`$ docker-compose run backend rails db:seed:replant fixture=all --trace`
<pre><code>
Creating yabs_backend_run ... done
** Invoke db:seed:replant (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Invoke db:truncate_all (first_time)
** Invoke db:load_config 
** Invoke db:check_protected_environments (first_time)
** Invoke db:load_config 
** Execute db:check_protected_environments
** Execute db:truncate_all
** Invoke db:seed (first_time)
** Invoke db:load_config 
** Execute db:seed
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke db:load_config 
** Execute db:abort_if_pending_migrations
** Execute db:seed:replant
david.jensen@itggot-1s2cois7 Yabs % docker-compose run backend rails db:seed:replant fixture=all --trace
Creating yabs_backend_run ... done
** Invoke db:seed:replant (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Invoke db:truncate_all (first_time)
** Invoke db:load_config 
** Invoke db:check_protected_environments (first_time)
** Invoke db:load_config 
** Execute db:check_protected_environments
** Execute db:truncate_all
** Invoke db:seed (first_time)
** Invoke db:load_config 
** Execute db:seed
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke db:load_config 
** Execute db:abort_if_pending_migrations
rails aborted!
ActiveRecord::RecordNotFound: Couldn't find Loan with 'id'=1
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/core.rb:177:in `find'
/app/db/seeds.rb:110:in `fixtures_user'
/app/db/seeds.rb:130:in `<main>'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:319:in `block in load'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:319:in `load'
/bundle/vendor/gems/railties-6.0.1/lib/rails/engine.rb:556:in `block in load_seed'
/bundle/vendor/gems/railties-6.0.1/lib/rails/engine.rb:676:in `with_inline_jobs'
/bundle/vendor/gems/railties-6.0.1/lib/rails/engine.rb:556:in `load_seed'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/tasks/database_tasks.rb:440:in `load_seed'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/railties/databases.rake:328:in `block (2 levels) in <main>'
/bundle/vendor/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
/bundle/vendor/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
/bundle/vendor/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
/bundle/vendor/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/bundle/vendor/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/bundle/vendor/gems/rake-13.0.1/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/bundle/vendor/gems/rake-13.0.1/lib/rake/task.rb:241:in `each'
/bundle/vendor/gems/rake-13.0.1/lib/rake/task.rb:241:in `invoke_prerequisites'
/bundle/vendor/gems/rake-13.0.1/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/bundle/vendor/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/bundle/vendor/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
/bundle/vendor/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
/bundle/vendor/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/bundle/vendor/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
/bundle/vendor/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
/bundle/vendor/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
/bundle/vendor/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
/bundle/vendor/gems/railties-6.0.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/bundle/vendor/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/bundle/vendor/gems/railties-6.0.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/bundle/vendor/gems/railties-6.0.1/lib/rails/command.rb:48:in `invoke'
/bundle/vendor/gems/railties-6.0.1/lib/rails/commands.rb:18:in `<main>'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `block in require'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `require'
/app/bin/rails:10:in `<top (required)>'
/bundle/vendor/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
/bundle/vendor/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
/bundle/vendor/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
/bundle/vendor/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
/bundle/vendor/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
/bundle/vendor/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
/bundle/vendor/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/app/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:seed:replant => db:seed
</code></pre>
`$ docker-compose run backend rails db:seed:replant --trace`
<pre><code>
Creating yabs_backend_run ... done
** Invoke db:seed:replant (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Invoke db:truncate_all (first_time)
** Invoke db:load_config 
** Invoke db:check_protected_environments (first_time)
** Invoke db:load_config 
** Execute db:check_protected_environments
** Execute db:truncate_all
** Invoke db:seed (first_time)
** Invoke db:load_config 
** Execute db:seed
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke db:load_config 
** Execute db:abort_if_pending_migrations
** Execute db:seed:replant

</code></pre>

### PR DESCRIPTION
**Pull request by te4-jonathan-ronsten**
## ⚙️ What issue did you implement or fix?
Fixes #403 

## 📜 Summary
- Fixed seeder
- Updated README.md

## 📝 Type of change

Please delete options that are not relevant.

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## 💩 How can this implementation be improved?
- Seeder could run automatically when running API-tests locally

### CODE REVIEW

**Comment by itggot-linus-styren** [comment]
Please also check in Gemfile.lock if adding dependencies: https://stackoverflow.com/a/4151540/3013334

**Review by te4-adrian-almetun-smeds — APPROVED** [review]
Can't find anything wrong with this one so :+1:

**Comment by itggot-linus-styren** [comment]
Do we need to update the installation procedure in README.md? Will the rails db:seed command not be used?

**Comment by te4-david-jensen** [comment]
> Do we need to update the installation procedure in README.md? Will the rails db:seed command not be used?

rails db:seed exists inside of rails db:setup, which runs db:create, db:schema:load, and db:seed, which means that it could probably replace the latter 2 commands in setup

**Review by te4-alexander-kjellberg1 — APPROVED** [review]
Looks good, I like that you included how to reseed in the readme

**Pull request merged**
